apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
  namespace: wealthwise
spec:
  template:
    spec:
      containers:
        - image: 'quay.io/rh-ee-dwaters/ww-frontend:latest'