apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: investment-advisor
  namespace: wealthwise
spec:
  template:
    spec:
      containers:
        - env:
            # NOTE: This CORS configuration is not safe and should only be used in Dev
            - name: QUARKUS_HTTP_CORS
              value: 'true'
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: '*'
          envFrom:
            - secretRef:
                name: openai-token
          image: 'quay.io/rh-ee-dwaters/ww-investment-advisor:latest'