apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: investment-advisor
  namespace: wealthwise
spec:
  template:
    spec:
      containers:
        - env:
            # NOTE: This CORS configuration is not safe and should only be used in Dev
            - name: QUARKUS_HTTP_CORS
              value: 'true'
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: '*'
            # This setting should point at the Kafka Bootstrap Server used to send
            # Kafka history events to the add-history function
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
          envFrom:
            - secretRef:
                name: openai-token
          image: 'quay.io/rh-ee-dwaters/ww-investment-advisor:latest'